# Generated by Django 4.1.5 on 2023-01-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancer', models.TextField(max_length=200)),
                ('detalles', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.TextField(max_length=10)),
                ('nombres', models.TextField(max_length=150)),
                ('tipo', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.TextField(max_length=10)),
                ('nombres', models.TextField(max_length=150)),
                ('fecha_nac', models.DateField(verbose_name='fecha de nacimiento')),
                ('genero', models.TextField(max_length=10)),
                ('telefono', models.PositiveIntegerField(default=0)),
                ('direccion', models.TextField(max_length=250)),
                ('estado_per', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gastos', models.TextField(max_length=100)),
                ('detalles_gastos', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.TextField(max_length=150)),
                ('id_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.persona')),
            ],
        ),
        migrations.CreateModel(
            name='OtrosGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_gasto_o', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto_o', models.DateField(verbose_name='fecha otros gastos')),
                ('descripcion_gastos', models.TextField(max_length=350)),
                ('comprobante_gasto_o', models.FileField(upload_to='uploads/')),
                ('id_voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='GastoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_gasto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateField(verbose_name='fecha gasto')),
                ('motivo', models.TextField(max_length=150)),
                ('comprobante_gasto', models.FileField(upload_to='uploads/')),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiario')),
                ('id_tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.tipogasto')),
                ('id_voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_donacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_donacion', models.DateField(verbose_name='fecha donacion')),
                ('num_cta', models.TextField(max_length=20)),
                ('comprobante_donar', models.FileField(upload_to='uploads/')),
                ('id_donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.donante')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_presuntivo', models.TextField(max_length=200)),
                ('detalles', models.TextField(max_length=350)),
                ('fecha_diagnostico', models.DateField(verbose_name='fecha diagnostico')),
                ('documento', models.FileField(upload_to='uploads/')),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiario')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='id_cancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.cancer'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='id_perso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.persona'),
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiario')),
                ('id_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.persona')),
            ],
        ),
    ]
