# Generated by Django 4.1.5 on 2023-02-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancer',
            options={'verbose_name': 'Cancer', 'verbose_name_plural': 'Canceres'},
        ),
    ]
