# Generated by Django 4.1.5 on 2023-02-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200, verbose_name='Tipo de cancer')),
                ('description', models.TextField(max_length=350, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Cancer',
                'verbose_name_plural': 'Canceres',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, verbose_name='dni')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('birthday', models.DateField(verbose_name='fecha de nacimiento')),
                ('gender', models.CharField(max_length=10, verbose_name='genero')),
                ('phone', models.CharField(max_length=10, verbose_name='telefono')),
                ('address', models.TextField(max_length=250, verbose_name='direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaryapp.cancer')),
                ('id_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaryapp.person')),
            ],
        ),
    ]
