# Generated by Django 4.1.5 on 2023-02-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaryapp.beneficiary')),
                ('id_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaryapp.person')),
            ],
        ),
    ]
