# Generated by Django 4.1.5 on 2023-02-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0002_companion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=150, verbose_name='nombre')),
                ('type_donor', models.TextField(max_length=20, verbose_name='Tipo de donador')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_donation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto de la donacion')),
                ('date_donation', models.DateField(verbose_name='fecha donacion')),
                ('num_cta', models.TextField(max_length=20)),
                ('voucher_dona', models.FileField(upload_to='uploads/')),
                ('id_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaryapp.donor')),
            ],
        ),
    ]
