# Generated by Django 4.1.5 on 2023-02-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0003_donor_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField(max_length=150, verbose_name='cargo')),
                ('id_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaryapp.person')),
            ],
        ),
    ]
