# Generated by Django 4.1.5 on 2023-02-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0006_type_expense_expensebeneficiary_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=1, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='id_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaryapp.cancer'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='document',
            field=models.FileField(upload_to='uploads', verbose_name='documento'),
        ),
    ]
