# Generated by Django 4.1.5 on 2023-02-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0007_person_active_alter_beneficiary_id_cancer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebeneficiary',
            name='id_type_expense',
        ),
        migrations.AddField(
            model_name='donation',
            name='active',
            field=models.BooleanField(default=1, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='donor',
            name='active',
            field=models.BooleanField(default=1, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='expense',
            name='active',
            field=models.BooleanField(default=1, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='expense',
            name='type_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaryapp.companion'),
        ),
        migrations.AddField(
            model_name='expensebeneficiary',
            name='finalized',
            field=models.BooleanField(default=1, verbose_name='finalizado'),
        ),
        migrations.AddField(
            model_name='expensebeneficiary',
            name='id_companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaryapp.companion'),
        ),
    ]
