# Generated by Django 4.1.5 on 2023-02-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0008_remove_expensebeneficiary_id_type_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaryapp.type_expense'),
        ),
    ]
