# Generated by Django 4.1.5 on 2023-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0009_alter_expense_type_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensebeneficiary',
            name='active',
            field=models.BooleanField(default=1, verbose_name='activo'),
        ),
    ]
