# Generated by Django 4.1.5 on 2023-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0012_alter_diagnostic_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Origen'),
        ),
    ]
