# Generated by Django 4.1.5 on 2023-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0013_beneficiary_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='file_solicitud',
            field=models.FileField(blank=True, null=True, upload_to='solicitud/', verbose_name='solicitud de inclusión'),
        ),
    ]
