# Generated by Django 4.1.5 on 2023-05-02 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaryapp', '0014_beneficiary_file_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id_voluntary',
        ),
        migrations.RemoveField(
            model_name='expensebeneficiary',
            name='id_voluntary',
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=80, verbose_name='Nombre del banco')),
                ('account_number', models.CharField(max_length=80, verbose_name='Numero de cuenta')),
                ('id_perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaryapp.person')),
            ],
        ),
    ]
